Factory.define :project, :class => TicketMaster::Provider::Github::Project do |p|
    p.description ''
    p.url '' 
    p.forks '' 
    p.name  'project name'
    p.homepage  ''
    p.watchers  ''
    p.private  ''
    p.fork  ''
    p.open_issues ''  
    p.pledgie  ''
    p.size  ''
    p.actions '' 
    p.score  ''
    p.language  ''
    p.followers  ''
    p.type  ''
    p.username  ''
    p.id  ''
    p.pushed  ''
    p.created  ''
end