Factory.define :repository do |p|
    p.description ''
    p.url '' 
    p.forks '' 
    p.name  'test-juange'
    p.homepage  ''
    p.watchers  ''
    p.private  ''
    p.fork  ''
    p.open_issues ''  
    p.pledgie  ''
    p.size  ''
    p.actions '' 
    p.score  ''
    p.language  ''
    p.followers  ''
    p.type  ''
    p.username  'juanespinosa'
    p.id  ''
    p.pushed  ''
    p.created  ''
end
